### ISSUE TITLE
Problems with library dependencies

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#10]
I want to implement one example from internet (from 2015).

What should I do to overcome this error?

**Comment by tdgunes** [comment]
Can you add more details about your problem?

For instance:

- Which example are you trying to implement?
- What type of libraries is the example using? 
- Some screenshots would be nice. (You can drag & drop images to comment section in Github.)

**Comment by yustiks** [comment]
agent: 
![question](https://user-images.githubusercontent.com/2270085/32837326-053845f6-ca05-11e7-9d0c-5961c1706606.png)
anac2015.TUDMixedStrategyAgent

**Comment by yustiks** [comment]
![question1](https://user-images.githubusercontent.com/2270085/32837392-4b4f9b34-ca05-11e7-9caa-72211c75daae.png)

**Comment by yustiks** [comment]
![question2](https://user-images.githubusercontent.com/2270085/32837434-77346806-ca05-11e7-998d-b038cf81969f.png)

**Comment by tdgunes** [comment]
I think I can help you better if we meet in person. Why don't you come to the hands-on session on Thursdays?

**Comment by yustiks** [comment]
Thank you!
