### ISSUE TITLE
Is reservation value a dynamic value? 

### ISSUE THREAD

**Issue by dahuangshebao** [tdgunes/ExampleAgent#14]
I saw the explanation of the usage of getReservationValue func. What is the reservation value and I am confused that it is a constant value or a dynamic value?
![809579b7-9e9e-4d93-92e8-868c3585bba7](https://user-images.githubusercontent.com/15828155/32779850-24d1cdca-c937-11e7-96c5-698202e3535e.png)

**Comment by tdgunes** [comment]
First, in the coursework, reservation values are not going to be used. Enrico sent an email about this. Please check that email to learn more about the domains.

For your question, that part in javadoc is trying to explain that if there is also a discount factor in addition to reservation value, the reservation value decreases over the time.
