### ISSUE TITLE
When the objects of the agents are created?  

### ISSUE THREAD

**Issue by dahuangshebao** [tdgunes/ExampleAgent#15]
Is every round the system create(new) a object of agent and at the end of the round it will be destroyed? Or does the genius system call init func every round?

**Comment by tdgunes** [comment]
Each negotiation session (which consists of a number of rounds), GENIUS creates the object of an agent. 

The number of rounds depends on the negotiation setting, take a look here to learn more about [how to keep track of time](https://github.com/tdgunes/ExampleAgent/wiki/Keeping-track-of-time).  In the coursework, it is going to be 180 seconds, which allows quite a lot of rounds.
