### ISSUE TITLE
Implementation of example agent

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#16]
I try to implement the agent, but it doesn`t work in Ubuntu. I tried to do it manually. What can be the reason? 
The loaded class seems to be of the wrong type. 
ExampleAgent cannot be cast to negotiator.Agent

**Comment by tdgunes** [comment]
Can you check the issue #4?

**Comment by yustiks** [comment]
thank you, i just reinstalled my system from Windows to Ubuntu, and tried to install in here, it helped
