### ISSUE TITLE
script to run lots of tournaments

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#17]
How can I run a load of tournaments to get a set of log files to analyse the data from?

Cheers,

Jo

**Comment by tdgunes** [comment]
Hi Jo,

You can run a set of tournaments from command line.  There is [a wiki page ](https://github.com/tdgunes/ExampleAgent/wiki/Running-a-negotiation-session-via-command-line) about it.  

The example xml configuration in that page is for only running  a single tournament, but you can add a couple of more by adding multiple `<tournament>` elements. Basically you can copy and paste the original `tournament` element and edit the new elements (_for instance tournaments with different domains and agents_).   The rest is same as mentioned in the wiki page.

**Comment by tdgunes** [comment]
Closing the issue
