### ISSUE TITLE
Access our evaluation of each item in an issue

### ISSUE THREAD

**Issue by TheoVerhelst** [tdgunes/ExampleAgent#18]
To continue on the same subject as #5, is there a way to explicitly know our evaluation of each single item in an issue, according to our preference profile?

For example, if we have the preference profile given in the wiki page [Domains & Preference Profiles](https://github.com/tdgunes/ExampleAgent/wiki/Domains-&-Preference-Profiles), you explained in #5 how to get the weight of each issue, but not how to get the evaluation of, say, the item "Chips and Nuts" in the issue "Food"

    <issue index="1" name="Food" type="discrete">
        <item value="Chips and Nuts" evaluation="3"></item>
        ...
    </issue>

I checked in the API but couldn't find anything relevant.

**Comment by kinetiz** [comment]
I've got the same problem. Just found only 
utilitySpace.getEvaluation(IssueNumber, Bid), which can get Evaluation only a specified Bid.
Is there any better ways to do this?

**Comment by tdgunes** [comment]
I prepared [a new wiki page ](https://github.com/tdgunes/ExampleAgent/wiki/Accessing-the-evaluation-of-a-value)about this. Let me know if the page makes it clear.

**Comment by TheoVerhelst** [comment]
That's perfect, thank you! :bowing_man:
