### ISSUE TITLE
Classes: Agent & AbstractNegotiationParty

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#20]
There are a lot of papers describe Class Agent . Is it the same as AbstractNegotiationParty? I mean can we use it instead of ? Or is it compulsory to use AbstractNegotiationParty?

**Comment by tdgunes** [comment]
Class `Agent` is used for bi-lateral (two agents) negotiation scenarios, for your agent to work in multiparty (more than 2 agents) negotiation scenarios, it must use `AbstractNegotiationParty`. But I think you can get inspirations from those papers.

**Comment by yustiks** [comment]
thanks
