### ISSUE TITLE
Is it possible to use System.out.println?

### ISSUE THREAD

**Issue by rashedkoutayni** [tdgunes/ExampleAgent#21]
Is it possible to use System.out.println in my agent class for debugging? Where will the output be displayed?

**Comment by tdgunes** [comment]
Yes,  make sure that `System.out.println` is enabled, during negotiation session you're going to see the output in the `Run Toolbar` of Intellij. (If you're running GENIUS from the terminal, the output must be in that terminal session.)  As shown below:

![2017-11-22-145906_3840x1080_scrot](https://user-images.githubusercontent.com/136392/33133959-56cbe2a6-cf96-11e7-8571-a00f4be5c976.png)

Also take a look at the wiki page, [how to debug your agent](https://github.com/tdgunes/ExampleAgent/wiki/Debugging-your-negotiating-agent).
