### ISSUE TITLE
Question about how to calculate the mark

### ISSUE THREAD

**Issue by dahuangshebao** [tdgunes/ExampleAgent#22]
I'm confusing how to calculate the mark.
There are two situation, first， we all at Nash point, second, i have the best utility and we are in pareto.
SO, in these two situation, which one can get the best mark?

**Comment by tdgunes** [comment]
This is a question about particularly coursework (therefore, it is better to write this to the student wiki page to get a clear answer.) But let me try to explain briefly here:

**Distance to nash point** is a metric that denote the **social welfare (fairness)** between all parties. If your agent is selfish all the time (_offering the best bid for itself)_, you should expect your agent to have a higher distance to nash point (_which is not good._). 

To get the best mark, you should **make a compromise between being selfish and being fair to other parties**. If your agent can predict what its opponent's preference profile better, (This is usually called as _opponent modelling_.)  you should be able to get an estimate of the nash point. After that, tuning your agents's selfish level, such that your agent **generates bids that are somewhere around pareto frontier _in theory_ must get you the best mark**.  

The reason, why I am saying _in theory_ is that there can be irrational agents, acting randomly. You need to take that into account too.
