### ISSUE TITLE
Calculating the nash point

### ISSUE THREAD

**Issue by dahuangshebao** [tdgunes/ExampleAgent#24]
Hi Taha, I have one question which is how to calculate the Nash point, if i can guess the opponent's preferences.

**Comment by tdgunes** [comment]
Hi there,

If your agent can make utility estimations about every possible offer inside a domain for each agent,  you can find the nash point with a brute force way by (in _pseudo code_):

```pseudo
maxUtility = 0;
nashOffer = null;
for each possible `bid`:
     p = 1.0;
     for each `agent` in the negotiation: 
           // note that if `agent` is your agent, it is not an estimate 
           p *= get the utility estimate of `bid` with respect to  `agent`
     if p > maxUtility:
           nashOffer = `bid`;
           maxUtility = p;

returns nashOffer;
```

_As as a side note, consider the fact that the domain might be very big, therefore calculating the nash bid in each round might be not the best thing to do._

**Comment by yustiks** [comment]
than the question is how to calculate nash distance in a best way )))))

**Comment by tdgunes** [comment]
@yustiks Can you open a new issue for this question?
