### ISSUE TITLE
What's the meaning of the type?

### ISSUE THREAD

**Issue by dahuangshebao** [tdgunes/ExampleAgent#25]
Hi, Taha. I see the type in issue which i received is 'discrete', and i look up the API and see the types of issue. I don't know the meaning of the type. Could you explain the type or could you tell which one we will use
![50d0275f-fc28-4de5-ac78-6911fdfd3e1a](https://user-images.githubusercontent.com/15828155/33226107-973e6096-d17d-11e7-96ae-57fc1ef5a8b4.png)
Thank you very much

**Comment by tdgunes** [comment]
Hi there,

Only **discrete** issues are going to be used in the coursework. Enrico sent an email about this. Please check your inbox, also have a look at [this page](https://github.com/tdgunes/ExampleAgent/wiki/Issue-&-Value-Types) for the type.
