### ISSUE TITLE
Use of maven dependencies

### ISSUE THREAD

**Issue by Chreschtf** [tdgunes/ExampleAgent#26]
Can we add maven dependencies to our project or will that cause some issue?

**Comment by tdgunes** [comment]
Yes, however make sure that the dependencies are included inside your agent's `jar` package.

**Comment by nb8g13** [comment]
When I try to add the class for my Agent to GENIUS, it immediately throws an error because the classes I use from my Maven dependencies can't be found. How can I add my agent to GENIUS so that I can test it?

**Comment by tdgunes** [comment]
Hi there,

I've just created [a new branch called `maven`](https://github.com/tdgunes/ExampleAgent/tree/maven) in this repository. By checking that branch out (have a look at the [README.md](https://github.com/tdgunes/ExampleAgent/blob/maven/README.md)), you should be able to create a jar package with all dependencies inside without any problems.

**Comment by tdgunes** [comment]
@nb8g13 I've just sent [a new commit](https://github.com/tdgunes/ExampleAgent/commit/7a84d39d5628198c3485cea3902b61229be27a21), now it adds source files of your agent too. 

In any case, you should submit your agent beforehand to see if it is packaged correctly.

**Comment by nb8g13** [comment]
Thanks Taha, although right now I am getting this error? 

![image](https://user-images.githubusercontent.com/25404404/33501138-5c09b308-d6d3-11e7-9eb8-116cdde6ffd5.png)

**Comment by nb8g13** [comment]
Thank you Taha. 

Just a note for anyone using Windows and Maven. You will need to replace the ":" for ";" in order to test your code.

**Comment by Chreschtf** [comment]
Hello Taha,
we settled for a non-maven dependency, is there any change for the creation of the jar ? we can run it on our pc (only using eclipse, not intellij) but when submitting it we still get an NoClassDefFoundError...

**Comment by Chreschtf** [comment]
Ok nevermind, we got rid of the dependency :)

**Comment by tdgunes** [comment]
@nb8g13 Do you mean this statement?

```
java -cp negosimulator.jar;agent1.jar negotiator.xml.multipartyrunner.Runner multilateraltournament.xml
```

If so, it would be better for me to write this in the README.md.
