### ISSUE TITLE
Single negotiation session log files

### ISSUE THREAD

**Issue by guibvieira** [tdgunes/ExampleAgent#27]
HI, I've been having a look at the log files and i get something really weird. They always start by betting really low even though the Example Agent is supposed to offer max utility at the beginning and they always offer the same bids at each other. Would you be able to have a look to the file and tell me where i could be going wrong?

[Log-Session_20171128-103324.xlsx](https://github.com/tdgunes/ExampleAgent/files/1509478/Log-Session_20171128-103324.xlsx)

**Comment by tdgunes** [comment]
If you run a single multi-party negotiation session, two log files are created:

**Log-Session_{date-time}.csv**: Only outputs rounds, turns, normalized time, name of the agent, the current offer
**Log-Session_{date-time}.xml**: Number of bids, final utility of the agent and etc.

You should take a look at the GUI for the offers that were given in the rounds and their utilities. I think a better approach to evaluate your agent is running multiple negotiation sessions (i.e tournaments).
