### ISSUE TITLE
Import statement of a new class file

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#29]
I want to create folder with class , that will be used by agent. How should I address it? 
For example, I have folder bin and the class CalcBid.class in it. 
How should I access it?

**Comment by tdgunes** [comment]
Why does your agent require an access to the file system?

**Comment by yustiks** [comment]
Sorry for my English. It is not about access. 
I wrote extra class for my agent. 
How should the address to my class look like? 
For example, I have a folder named "classes" and class named "Temp.class" in it. 
Can I import it only by "import classes.Temp;" ??

**Comment by tdgunes** [comment]
The IDE that you're using should be able to insert the import statement automatically when you are using that class inside your main agent class. I think I can help you better if you can come to the session tomorrow.
