### ISSUE TITLE
How do we iterate through all bids in a domain?

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#3]
If we want to find out what preferences the others have, wouldn't it be a good idea to change the offer each time by conceding on just one issue, to see if the opponents reacted at all..

**Comment by tdgunes** [comment]
I am guessing you are asking two questions:

The first one is `"How do we iterate through the issues in a bid?"` and the second one is `"Wouldn't it be a good idea to change the offer each time by conceding on just one issue, to see if the opponents reacted at all?"`

For your first question, I am going to add a new code snippet to FAQs in wiki.  About your second question, why don't you make some experiments and see whether that strategy works or not?

**Comment by jogrundy** [comment]
Yes, you're right, that was two questions. Cheers,

jo

**Comment by jogrundy** [comment]
Ooh I found this:
BidIterator bidit = new BidIterator(this.utilitySpace.getDomain());
seems to be what I want..

**Comment by tdgunes** [comment]
@doctorjo thanks for that. FYI, Javadoc for `BidIterator`:

> For issues with a continuous range **discretization is used**. If you want to search the set of generated bids efficiently, consider using SortedOutcomeSpace instead.

**Comment by jogrundy** [comment]
Thanks, I’ll have a look in to it now.

Cheers again!

Jo

**Comment by tdgunes** [comment]
BTW, to iterate the each issue and value take a look [here](https://github.com/tdgunes/ExampleAgent/wiki/Changing-the-content-of-a-given-bid).

**Comment by jogrundy** [comment]
Thats brilliant! Really useful, I’m sure lots of people will find that helpful!

Jo
