### ISSUE TITLE
Papers 

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#30]
Taha, I also wanted to ask whether you have some papers from previous agents. 
I found a good book, but I have no access to it. 
Do you have some papers from this book? 
http://www.springer.com/gb/book/9783319515618
I am particularly interested in this agent

Atlas3: A Negotiating Agent Based on Expecting Lower Limit of Concession Function

and this one

Pars Agent: Hybrid Time-Dependent, Random and Frequency-Based Bidding and Acceptance Strategies in Multilateral Negotiations

**Comment by tdgunes** [comment]
@yustiks can you send me your university email address via email?

**Comment by yustiks** [comment]
I found this book
