### ISSUE TITLE
A question of 'Accessing the evaluation of a value'

### ISSUE THREAD

**Issue by GreatGBL** [tdgunes/ExampleAgent#31]
Hello, I can not run the Example Programming (API) in 'Accessing the evaluation of a value'

I just copy and paste the code ,but the last line 'System.out.println("Evaluation(getEvaluation): " + evaluatorDiscrete.getEvaluation(valueDiscrete));' does not work.

Error:(157, 103) java: unreported exception java.lang.Exception; must be caught or declared to be thrown

Therefore, I have to create a matrix to save each max value on evaluation. I want to find a help, why the example in WIKI does not work?

**Comment by tdgunes** [comment]
You need to put a try-catch clause to that line (IDEs usually automatically detect this):

```java
try {
    System.out.println("Evaluation(getEvaluation): " + evaluatorDiscrete.getEvaluation(valueDiscrete));
} catch (Exception e) {
    e.printStackTrace();
}
```
