### ISSUE TITLE
Get a bid value and compare them

### ISSUE THREAD

**Issue by zaneghost** [tdgunes/ExampleAgent#33]
I am having a hard time trying to figure out how to get issue items(e.g. Catering, handmade food, or chips) and compare them, I have tried a lot of methods such as bid.getValue.

Can anyone help?

**Comment by tdgunes** [comment]
[This page](https://github.com/tdgunes/ExampleAgent/wiki/Accessing-the-evaluation-of-a-value) explains how to get issue items and provides an example code. To get the name of the values rather than evaluation value, you need to use `valueDiscrete.getValue()` method.

**Comment by zaneghost** [comment]
But I am assuming one certain issue of one certain Bid can only have one value(e.g. Catering, handmade food, or chips) right? The provided code gives us how to get all issue values of one domain, am I missing anything or I am not allowed to get the certain value? I can see the bid is using a hashtable to store the values, and the value, by examining the Value class file, does not provide a getter to show its name or anything identifiable.

**Comment by tdgunes** [comment]
Have a look at the `getValue` method in the javadocs. But you need to store issue numbers to fetch the values.
