### ISSUE TITLE
Ubuntu log files

### ISSUE THREAD

**Issue by yustiks** [tdgunes/ExampleAgent#34]
Hello. 
I am using Ubuntu and can`t find log file in my log folder. 
Where can it be?

**Comment by tdgunes** [comment]
Logs are _usually_ located in `ExampleAgent/genius/log` and `ExampleAgent/genius/logs`. If you're running from negotiations from the terminal, you should check the path that you provided.

**Comment by yustiks** [comment]
I run not from the terminal

**Comment by yustiks** [comment]
I solved this problem. It was just the second folder with another genius.
