### ISSUE TITLE
Questions regarding estimating Utility under uncertainty

### ISSUE THREAD

**Issue by shford7** [tdgunes/ExampleAgent#39]
Hi I was trying to access weight and value of issues when uncertainty is enabled using the APIs in the wiki and the snippet from Lab 5.  I understand that we can't get both weight and values because we would be able to calculate the utility with them, while we don't know the actual utility of the bids provided. However, I kept getting error 'NullPointerException' from the line `EvaluatorDiscrete`evaluator = (EvaluatorDiscrete) additiveUtilitySpace.getEvaluator(issuenumber);.`  I enabled the 'uncertainty option' of preference profiles and I added try catch method to handle exceptions.  Not sure if it's because that neither weight nor value/evaluation can be obtained under uncertainty or it's just errors in code. Thank you!

**Comment by shford7** [comment]
![image](https://user-images.githubusercontent.com/26031143/48787721-3ffad500-ece1-11e8-9f54-126d03bb78a8.png)

**Comment by tdgunes** [comment]
Yes, like as you said: If the preference profile is a partially ordered (uncertainty is checked.), then you can not access the evaluators. More on this is included in [Lab 2](https://tdgunes.com/COMP6203-2018Fall/Lab2/index.html).
