### ISSUE TITLE
java.lang.ClassCastException: ExampleAgent cannot be cast to negotiator.Agent

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#4]
So I tried changing something and adding the agent, but got this error message. 
I then tried repasting in the original code, rebuilding, then adding the agent, and got the same message..

Then I tried again, setting up a new project, pasting in the code as in your video tutorial, and still get the same error message when I try to add the agent (in this case, ExampleAgent3) to the simulator. 

Have you any idea what could be happening?

<img width="996" alt="screen shot 2017-10-27 at 09 58 13" src="https://user-images.githubusercontent.com/29311507/32096165-84f15eca-bafd-11e7-862b-84ed2e3fc78f.png">

**Comment by tdgunes** [comment]
@doctorjo I think you are trying to add your agent into wrong `Agents` tab.  Can you please try adding your agent to `Parties` tab?

`Agents` tab is for bilateral agents that use `negotiator.Agent` class. But we are going to use `AbstractNegotiationParty` class.

**Comment by jogrundy** [comment]
Oops!

thank you, sorry for being daft

Jo
