### ISSUE TITLE
Running-a-negotiation-session-via-command-line

### ISSUE THREAD

**Issue by RickRe** [tdgunes/ExampleAgent#40]
https://github.com/tdgunes/ExampleAgent/wiki/Running-a-negotiation-session-via-command-line

Hi,

I wish to run the negotiation via command line so that I don't have to click again and again on the GUI.
Does the system support "Enable System.out print" while running via command line? I need the print information to do debug.
Thank you very much.

BR.
Rick

**Comment by Carlos487** [comment]
I agree that it could be useful for debugging purposes, it seems that when it uses the Runner class it ignores that setting as it isn't a way to configure it in the xml file. Please your help with this issue.

**Comment by tdgunes** [comment]
I will have a look at this in detail. I guess, it might require some changes in the platform if that is the case. Meanwhile you can save logs to a file by using [PrintWriter](https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html).

**Comment by RickRe** [comment]
Thank you very much. I will use PrintWriter.
