### ISSUE TITLE
Negotiation crashing when Uncertainty enabled but preference profile Nro. Rankings is 0

### ISSUE THREAD

**Issue by Carlos487** [tdgunes/ExampleAgent#41]
When this value is 0, the call to the parent constructor of AbstractNegotiationParty, tries to makes the following calls

> AbstractNegotiationParty() CTOR -> estimateUtilitySpace() -> estimateUsingBidRanks() -> normalizeWeightsByMaxValues() ->normalizeAll()

In the last one **normalizeAll()** from the **EvaluatorDiscrete()** class it crashes, so this case should be handled or reported as an exception to the system.output, because currently you get the usual null popup with no additional information, and finding the real error could be time consuming. Other solution would be to allow ranking numbers greater than 0.

We manage to sort out the error, using a number of rankings greater than 0,  but it should be useful to report as a bug to Genius Platform.

    public void normalizeAll() {
        double var1 = (Double)this.fEval.get(this.getMaxValue());
        this.fEval.forEach((var3, var4) -> {
            Double var10000 = (Double)this.fEval.put(var3, (Double)this.fEval.get(var3) / var1);
        });
        this.setWeight(var1);
    }

**Comment by tdgunes** [comment]
Thanks for reporting this and sorry for the late reply. I fixed this bug yesterday and sent the patch to the maintainers. The competition will be on the modified version of Genius.
