### ISSUE TITLE
Is there a way to access your own utility weights?

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#5]
I can see the weights in the party domain xml file, but do I have to parse this file to access the weights or is there a better way?
Cheers, Jo

**Comment by tdgunes** [comment]
Hi Jo, 

You must access weights of each issue via Genius API. 

Can you try this and let me know whether this works:
```java
AbstractUtilitySpace utilitySpace = info.getUtilitySpace();
AdditiveUtilitySpace additiveUtilitySpace = (AdditiveUtilitySpace) utilitySpace;

List<Issue> issues = additiveUtilitySpace.getDomain().getIssues();

for (Issue issue : issues) {
    System.out.println(additiveUtilitySpace.getWeight(issue.getNumber()));
}
```

There can be different types of utility spaces, in this coursework (also in the international competition ANAC), `AdditiveUtilitySpace` is used.

**Comment by jogrundy** [comment]
Hi Taha

I got this error message when trying to build, after making sure both abstract and additive utility space were imported:

Error:(84, 45) java: info has private access in negotiator.parties.AbstractNegotiationParty
Error:(87, 14) java: cannot find symbol
  symbol:   class Issue
  location: class ExampleAgent
Error:(89, 14) java: cannot find symbol
  symbol:   class Issue
  location: class ExampleAgent

where lines 84 - 91 were the lines pasted in to otherwise working code.

I’m trying to work around it now..

Jo

**Comment by tdgunes** [comment]
@doctorjo make sure `info` is accessible. For example:

![2017-10-30-163510_3000x1920_scrot](https://user-images.githubusercontent.com/136392/32183132-60c30a22-bd90-11e7-87ac-a7e5ae46283a.png)

**Comment by jogrundy** [comment]
I got this to work

        AdditiveUtilitySpace additiveUtilitySpace = (AdditiveUtilitySpace) utilitySpace;

        List<Issue> issues = additiveUtilitySpace.getDomain().getIssues();

        for (Issue issue : issues) {
            System.out.println(additiveUtilitySpace.getWeight(issue.getNumber()));
        }
after making sure I imported negotiator issue.Issue .. 
as it did not seem like AbstractUtilitySpace was used..
Thank you very much for your help again!

Jo

**Comment by tdgunes** [comment]
No worries, glad to hear that  it works. I'll add this to wiki.
