### ISSUE TITLE
Problems with command line tool

### ISSUE THREAD

**Issue by jogrundy** [tdgunes/ExampleAgent#7]
It doesn't seem to be actually exiting properly.. I get this:
<img width="1280" alt="screen shot 2017-11-03 at 11 02 55" src="https://user-images.githubusercontent.com/29311507/32370931-c395e806-c086-11e7-8d13-114ca6abedac.png">

**Comment by jogrundy** [comment]
Seems to finish, only taking three times the amount of time allowed in the tournament.

**Comment by tdgunes** [comment]
Can you post your xml file here?

**Comment by jogrundy** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<multilateralTournamentsConfiguration>
  <tournaments>
    <tournament>
      <deadline>
        <value>10</value>
        <type>TIME</type>
      </deadline>
      <protocolItem hasMediatorProfile="false" hasMediator="false"
        description="Each agents makes offer, counter-offer, or accepts"
        classPath="negotiator.protocol.StackedAlternatingOffersProtocol"
        protocolName="Stacked Alternating Offers Protocol for Multi-Lateral Negotiation (SAOPMN)" />
      <partyRepItems>
        <party classPath="../out/production/ExampleAgent/ExampleAgent.class">
          <properties />
        </party>
        <party classPath="agents.anac.y2015.pokerface.PokerFace">
          <properties />
        </party>
        <party
          classPath="agents.anac.y2015.TUDMixedStrategyAgent.TUDMixedStrategyAgent">
          <properties />
        </party>
      </partyRepItems>
      <partyProfileItems>
        <item url="file:etc/templates/partydomain/party1_utility.xml" />
        <item url="file:etc/templates/partydomain/party2_utility.xml" />
        <item url="file:etc/templates/partydomain/party3_utility.xml" />
      </partyProfileItems>
      <repeats>1</repeats>
      <numberOfPartiesPerSession>3</numberOfPartiesPerSession>
      <repetitionAllowed>false</repetitionAllowed>
      <persistentDataType>DISABLED</persistentDataType>
    </tournament>
  </tournaments>
</multilateralTournamentsConfiguration>

cut and paste, i only changed the time limit to 10 s

**Comment by jogrundy** [comment]
.. apparently not, and the xml code is not supported either, here is the text file.. like I said, cut and paste
[mlt.txt](https://github.com/tdgunes/ExampleAgent/files/1440918/mlt.txt)

**Comment by tdgunes** [comment]
Can you also quickly check the number of negotiation sessions in the log?

**Comment by jogrundy** [comment]
Interesting.. it seems to run 6 sessions, with a different order of bidding each time. 
I didn't know it would do that!

Jo

**Comment by tdgunes** [comment]
As far as I remember, it should be running permutations without repetitions of preference profile assignments, such that ‘P(3,3) = 6’. Apparently, that was the case with your xml file.
