### ISSUE TITLE
Getting other parties' ID

### ISSUE THREAD

**Issue by diegocervera** [tdgunes/ExampleAgent#9]
Is there a way of getting the names/ID of the other agents when the negotiation starts (before they send an offer)?

thanks

**Comment by tdgunes** [comment]
It seems like you can only get the number of parties by using this method: `public int getNumberOfParties()`. But during negotiation you can get the identifiers of agents by simply using a set/map to collect identifiers.

**Comment by diegocervera** [comment]
"But during negotiation you can get the identifiers of agents by simply using a set/map to collect identifiers."
How would you do that? I would like to get their names in the "public void init()" method. Would that be possible?

**Comment by tdgunes** [comment]
With the current API, you can not get the identifiers of agents in the `init()` method. But during the negotiation, you can get the identifiers of agents in the `receiveMessage(AgentID sender, Action act)` where the `sender` is the identifier of an agent. For example:

```java
public class ExampleAgent extends AbstractNegotiationParty {
    private final String description = "Example Agent";
    private Set<AgentID> identifiers = new HashSet<>();
    ...

    @Override
    public void receiveMessage(AgentID sender, Action act) {
        super.receiveMessage(sender, act);

        if (!identifiers.contains(sender)) {
            identifiers.add(sender);
        }
    ...

```

**Comment by diegocervera** [comment]
Thanks Taha. This seems to work fine.
